### PR TITLE
Domain and Department Dropdown Filter Changes

### PR DESCRIPTION
**Pull request by 94lavanya**

### CODE REVIEW

**Review by CanopusApps — CHANGES_REQUESTED** [review]
ViewImageViewKaizen.html changes were not correct.

**Comment by CanopusApps** [comment]
Please resolve all the conflicts.

**Review by 94lavanya — COMMENTED** [review]
Changed

**Comment by CanopusApps** [comment]
merge conflicts are present. Created new branch and checked in the code

**Pull request closed without merging**
